Repository PeerFlow-TeamA/peerflow-BE, pull requests merged in 2023-07, with the labels that each got.

#20 Feat/#2 : A_MAI_00 구현 완료
  build.gradle
  src/main/java/com/peer/missionpeerflow/controller/.keep
  src/main/java/com/peer/missionpeerflow/controller/MainController.java
  src/main/java/com/peer/missionpeerflow/dto/mapper/MainQuestionDTOMapper.java
  src/main/java/com/peer/missionpeerflow/dto/response/.keep
  src/main/java/com/peer/missionpeerflow/dto/response/MainQuestionDTO.java
  src/main/java/com/peer/missionpeerflow/repository/.keep
  src/main/java/com/peer/missionpeerflow/repository/MainRepository.java
  src/main/java/com/peer/missionpeerflow/service/.keep
  src/main/java/com/peer/missionpeerflow/service/MainService.java
Labels: API feature

#25 Fix/#21 [A_MAI_00] Request Body 에러시 4xx리턴 되도록 수정
  src/main/java/com/peer/missionpeerflow/controller/MainController.java
  src/main/java/com/peer/missionpeerflow/service/MainService.java
Labels: bug

#27 Feat/#24 - ErrorMessage 클래스 정의
  src/main/java/com/peer/missionpeerflow/controller/MainController.java
  src/main/java/com/peer/missionpeerflow/exception/errormessage/ErrorMessage.java
Labels: API feature

#32 Fix/#31 MainController 에러 수정 및 Exception 리팩토링
  src/main/java/com/peer/missionpeerflow/controller/MainController.java
  src/main/java/com/peer/missionpeerflow/dto/mapper/MainQuestionDTOMapper.java
  src/main/java/com/peer/missionpeerflow/dto/response/MainQuestionDTO.java
  src/main/java/com/peer/missionpeerflow/exception/GlobalControllerAdvice.java
  src/main/java/com/peer/missionpeerflow/exception/errormessage/ErrorMessage.java
Labels: API feature

#36 FEAT: B-WRI-01 게시글(질문) 수정 기능 추가 - #5
  src/main/java/com/peer/missionpeerflow/controller/QuestionController.java
  src/main/java/com/peer/missionpeerflow/dto/request/QuestionModifyDTO.java
  src/main/java/com/peer/missionpeerflow/repository/QuestionRepository.java
  src/main/java/com/peer/missionpeerflow/service/QuestionService.java
  src/main/java/com/peer/missionpeerflow/util/Category.java
Labels: API feature

#35 Feat/#34 : 전체조회 기능 추가
  src/main/java/com/peer/missionpeerflow/controller/MainController.java
  src/main/java/com/peer/missionpeerflow/dto/request/.keep
  src/main/java/com/peer/missionpeerflow/repository/MainRepository.java
  src/main/java/com/peer/missionpeerflow/service/MainService.java
Labels: API feature

#39 Answer 기능 구현 + 테스트 추가
  .gitignore
  .gradle/7.6.1/executionHistory/executionHistory.bin
  .gradle/7.6.1/executionHistory/executionHistory.lock
  .gradle/7.6.1/fileHashes/fileHashes.bin
  .gradle/7.6.1/fileHashes/fileHashes.lock
  .gradle/7.6.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build/classes/java/main/com/peer/missionpeerflow/MissionPeerflowApplication.class
  build/classes/java/main/com/peer/missionpeerflow/controller/QuestionController.class
  build/classes/java/main/com/peer/missionpeerflow/dto/request/QuestionCreateRequest.class
  build/classes/java/main/com/peer/missionpeerflow/entity/Answer.class
  build/classes/java/main/com/peer/missionpeerflow/entity/AnswerComment.class
  build/classes/java/main/com/peer/missionpeerflow/entity/BaseEntity.class
  build/classes/java/main/com/peer/missionpeerflow/entity/Question.class
  build/classes/java/main/com/peer/missionpeerflow/entity/QuestionComment.class
  build/classes/java/main/com/peer/missionpeerflow/exception/ConflictException.class
  build/classes/java/main/com/peer/missionpeerflow/exception/ForbiddenException.class
  build/classes/java/main/com/peer/missionpeerflow/exception/GlobalControllerAdvice.class
  build/classes/java/main/com/peer/missionpeerflow/exception/NotFoundException.class
  build/classes/java/main/com/peer/missionpeerflow/repository/QuestionRepository.class
  build/classes/java/main/com/peer/missionpeerflow/service/QuestionService.class
  build/classes/java/main/com/peer/missionpeerflow/util/Category.class
  build/classes/java/main/com/peer/missionpeerflow/util/CategoryAttributeConverter.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/peer/missionpeerflow/controller/AnswerController.java
  src/main/java/com/peer/missionpeerflow/controller/MainController.java
  src/main/java/com/peer/missionpeerflow/controller/QuestionController.java
  src/main/java/com/peer/missionpeerflow/dto/mapper/RequestAnswerDTOMapper.java
  src/main/java/com/peer/missionpeerflow/dto/request/AnswerCreateDTO.java
  src/main/java/com/peer/missionpeerflow/dto/request/AnswerDeleteDTO.java
  src/main/java/com/peer/missionpeerflow/dto/request/AnswerModifyDTO.java
  src/main/java/com/peer/missionpeerflow/entity/Answer.java
  src/main/java/com/peer/missionpeerflow/entity/Question.java
  src/main/java/com/peer/missionpeerflow/exception/GlobalControllerAdvice.java
  src/main/java/com/peer/missionpeerflow/exception/message/ErrorMessage.java
  src/main/java/com/peer/missionpeerflow/exception/message/SuccessMessage.java
  src/main/java/com/peer/missionpeerflow/repository/AnswerRepository.java
  src/main/java/com/peer/missionpeerflow/service/AnswerService.java
  src/test/java/com/peer/missionpeerflow/MissionPeerFlowAnswerAPITests.java
  src/test/java/com/peer/missionpeerflow/MissionPeerflowApplicationTests.java
  src/test/java/com/peer/missionpeerflow/utils/RequestBodyJSONGenerator.java
Labels: bug, API feature, test

#46 feat : AnswerComment 로직 구현
  src/main/java/com/peer/missionpeerflow/controller/AnswerCommentController.java
  src/main/java/com/peer/missionpeerflow/controller/AnswerController.java
  src/main/java/com/peer/missionpeerflow/dto/mapper/RequestUserRecordDTOMapper.java
  src/main/java/com/peer/missionpeerflow/dto/request/AnswerCommentCreateDTO.java
  src/main/java/com/peer/missionpeerflow/dto/request/AnswerCommentDeleteDTO.java
  src/main/java/com/peer/missionpeerflow/dto/request/AnswerCommentModifyDTO.java
  src/main/java/com/peer/missionpeerflow/dto/request/UserRecordDTO.java
  src/main/java/com/peer/missionpeerflow/entity/AnswerComment.java
  src/main/java/com/peer/missionpeerflow/entity/UserRecord.java
  src/main/java/com/peer/missionpeerflow/exception/message/ErrorMessage.java
  src/main/java/com/peer/missionpeerflow/repository/AnswerCommentRepository.java
  src/main/java/com/peer/missionpeerflow/service/AnswerCommentService.java
  src/main/java/com/peer/missionpeerflow/service/AnswerService.java
  src/main/java/com/peer/missionpeerflow/service/QuestionService.java
  src/main/java/com/peer/missionpeerflow/service/UserRecordService.java
Labels: API feature

#50 [FIX] C-DET-00 질문 상세조회 API 명세에 맞게 수정
  src/main/java/com/peer/missionpeerflow/dto/mapper/QuestionDetailAnswerDTOMapper.java
  src/main/java/com/peer/missionpeerflow/dto/mapper/QuestionDetailDTOMapper.java
  src/main/java/com/peer/missionpeerflow/dto/response/QuestionDetailAnswerDTO.java
  src/main/java/com/peer/missionpeerflow/dto/response/QuestionDetailDTO.java
  src/main/java/com/peer/missionpeerflow/service/QuestionService.java
Labels: API feature
